version: '3.9'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - POSTGRES_USER: baloo
      - POSTGRES_PASSWORD: junglebook
      - POSTGRES_DB: lenslocked
    ports: 
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=darcula
    ports:
      - 3333:8080